# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
  - master
  - releases/*
  - features/*

variables:
  uiSource: './'
  uiBuild: '$(uiSource)/dist'
  remotePath: '/home/sagedev/apps/$(Build.SourceBranchName)/'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: CmdLine@2
  inputs:
    script: 'touch .env'
    
- script: |
    pushd $(uiSource)
    npm install
    npm run build
    popd
  displayName: 'npm install and build'
  
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SAGEDEV'
    sourceFolder: '$(uiBuild)'
    contents: '**'
    targetFolder: '$(remotePath)'
    readyTimeout: '20000'
